version: '3'
services:
  web:
    build: .
    volumes:
      - ./src:/src
    ports:
      - "8000:5000"
    command: bash -c "export FLASK_APP=flaskr && export FLASK_DEBUG=1 && flask run --host=0.0.0.0"
